var express=require("express");
const { login,singUp,isLogin, welcome } = require("../controllers/auth");
const {getUser, updateUser} = require("../controllers/user");
var router=express.Router();
router.post("/signup",singUp);
router.post("/login",login);
router.get("/welcome",isLogin,welcome);
router.get("/user/:UserId",getUser);
router.put("/user/:UserId",isLogin,updateUser);
module.exports=router;